name: build-and-publish-pdfs

on:
  release:
    types: created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile xHPTDC8 User Guide
        uses: xu-cheng/latex-action@v3
        with:
          root_file: xHPTDC8_User_Guide.tex
          latexmk_use_lualatex: true
          # work_in_root_file_dir: true

      - name: Publish xHPTDC8
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: ./xHPTDC8_User_Guide.pdf
          target: ${{ secrets.TARGETPDFXHPTDC }}
          # strip_components: 2
          rm: true

      - name: Upload documentation as release asset
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./xHPTDC8_User_Guide.pdf
